# needed to prevent issue with prettier
default_language_version:
  node: 16.14.2

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black-jupyter

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # exclude: new_model_setup/MPAS/MPAS_scenario_testing/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.0
    hooks:
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
      #- id: nbqa-isort
      #  additional_dependencies: [isort==5.12.0]
